[package]
name = "ldap-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[http]
cainfo = "/home/c/workspace/ldap-proxy/test.pem"



[dependencies]

concread = "^0.4.4"
clap = { version = "4.5", features = ["derive", "env"] }
futures-util = { version = "^0.3.30", features = ["sink"] }
hashbrown = { version = "0.14", features = ["serde"] }
openssl = "^0.10.64"
serde = { version = "^1.0.197", features = ["derive"] }
#tikv-jemallocator = "0.5"
tokio = { version = "^1.36.0", features = ["rt", "rt-multi-thread", "macros", "net", "signal", "io-util"] }
tokio-util = { version = "^0.7.10", features = ["codec"] }
tokio-openssl = "^0.6.4"
tokio-rustls-acme = "*"
rcgen = "0.12"
toml = "^0.8.10"
thiserror = "1"
serde_json = "1"
anyhow = "1"
futures = "0.3"
tokio-stream = { version = "0.1.15",features = ["full"]}

tracing = { version = "^0.1.40", features = ["max_level_trace", "release_max_level_debug"] }

tracing-forest = { version = "0.1.6", features = ["chrono", "smallvec", "tokio"] }
tracing-subscriber = "0.3"

url = { version = "^2.5.0", features = ["serde"] }

ldap3_proto = { version = "0.4.3", features = ["serde"] }



uuid = { version = "1.7.0", features = ["serde"] }

[patch.crates-io]
# ldap3_proto = { path = "../ldap3/proto" }
# ldap3_proto = { git = "https://github.com/kanidm/ldap3.git", rev = "63b77d71ea5e210d8c016c3e60dffed7bd644116" }

