[package]
name = "ldap-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

concread = "^0.4.0"
clap = { version = "4.1", features = ["derive", "env"] }
futures-util = { version = "^0.3.21", features = ["sink"] }
hashbrown = { version = "0.14", features = ["serde"] }
openssl = "^0.10.57"
serde = { version = "^1.0.188", features = ["derive"] }
tikv-jemallocator = "0.5"
tokio = { version = "^1.24.2", features = ["rt", "rt-multi-thread", "macros", "net", "signal", "io-util"] }
tokio-util = { version = "^0.7.8", features = ["codec"] }
tokio-openssl = "^0.6.3"

toml = "^0.5.11"

tracing = { version = "^0.1.37", features = ["max_level_trace", "release_max_level_debug"] }

tracing-forest = { version = "0.1.6", features = ["chrono", "smallvec", "tokio"] }
url = { version = "^2.4.0", features = ["serde"] }

ldap3_proto = { path = "../ldap3/proto", version = "0.4.0", features = ["serde"] }
